org: gonzalinhogaucho
app: aws-node-project
service: spreadsheet-example

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(.env.yml):}

functions:
  write:
    handler: src/handler.write
    events:
      - http:
          path: /write
          method: POST

plugins:
  - serverless-offline